joint_state_ctrlr:
  type: joint_state_controller/JointStateController
  publish_rate: 30

left_steering_ctrlr:
  joint: left_steering_hinge_joint
  type: effort_controllers/JointPositionController
  pid: {p: 35.0, i: 0.0, d: 5.0}

right_steering_ctrlr:
  joint: right_steering_hinge_joint
  type: effort_controllers/JointPositionController
  pid: {p: 35.0, i: 0.0, d: 5.0}

left_front_wheel_ctrlr:
  joint: front_left_wheel_joint
  type: effort_controllers/JointVelocityController
  pid: {p: 10, i: 1.0, d: 0.0, i_clamp: 5.0}

right_front_wheel_ctrlr:
  joint: front_right_wheel_joint
  type: effort_controllers/JointVelocityController
  pid: {p: 10, i: 1.0, d: 0.0, i_clamp: 5.0}

left_rear_wheel_ctrlr:
  joint: rear_left_wheel_joint
  type: effort_controllers/JointVelocityController
  pid: {p: 10, i: 1.0, d: 0.0, i_clamp: 5.0}

right_rear_wheel_ctrlr:
  joint: rear_right_wheel_joint
  type: effort_controllers/JointVelocityController
  pid: {p: 10, i: 1.0, d: 0.0, i_clamp: 5.0}


